### PR TITLE
New method to render metabox

### PR DESCRIPTION
**Pull request by r-a-y**
Regarding #4, this PR uses the Select2 JS library to render group selection in the metabox.

Select2 allows us to use autocompletion to search for groups to add, rather than initially querying all groups to select via checkbox.

Here's a GIF showing how it works:
Image of new metabox

Let me know what you think.

### CODE REVIEW

**Comment by boonebgorges** [comment]
Love it.

**Comment by mkgold** [comment]
Very cool. My only UX comment is that I think that the X is usually aligned to the right (at least in the US), if it's possible for us to change that.

**Comment by christianwach** [comment]
Looks good to me too, @r-a-y.

@mkgold In defense of the left-aligned X, it seems to be consistent with the WordPress Admin UI. See, for example the Tags metabox:

screen shot 2015-04-02 at 15 42 11

**Comment by mkgold** [comment]
@christianwach Interesting and good point. Let's leave as is, then

**Comment by r-a-y** [comment]
@christianwach - One thing I haven't tested is the BP Group Hierarchy plugin with the new metabox.  I know you added some type of support for that.  Can you do some testing and let me know if anything needs to be adjusted to allow BP Group Hierarchy to work?

**Comment by christianwach** [comment]
@r-a-y Will do that this week - I've been away on an Easter break and am only now catching up on tasks.

**Pull request merged**
