### PR TITLE
Remove JS

### PR DESCRIPTION
**Pull request by r-a-y**
Since EO v2.13.0, we no longer need to add JS to dynamically set the group ID or displayed user ID.

We can use the new `'eventorganiser_fullcalendar_query'` filter to add our custom parameters.

Let me know what you think.

### CODE REVIEW

**Comment by boonebgorges** [comment]
Hi @r-a-y - These changes look fine to me (I was thinking of doing something similar) but they won't merge after I did a bunch of work this morning to build some JS stuff. Could you refresh?

**Comment by r-a-y** [comment]
Yeah, I just saw the changes for JS filtering.  Working on modifying the JS so the filtering will still work.

**Comment by r-a-y** [comment]
Done!  See commit  2764cd4.

**Comment by boonebgorges** [comment]
Thanks!

**Pull request closed without merging**
